import React,{useState} from "react";
import {validCornHistory} from "../services/cornHistory.js";
import {config} from "../services/cornData.js";
const num=v=>Number.isFinite(v)?v.toLocaleString("en-US",{maximumFractionDigits:2}):"—";
const pct=v=>Number.isFinite(v)?`${num(v*100)}%`:"—";
const progressNames={planted:["已播种","Planted"],emerged:["已出苗","Emerged"],silking:["已吐丝","Silking"],dough:["糊熟","Dough"],dented:["凹粒","Dented"],mature:["已成熟","Mature"],harvested:["已收获","Harvested"]};
const progressText=(progress,lang)=>progress?Object.entries(progress).map(([key,value])=>`${progressNames[key]?.[lang==="zh"?0:1]??key} ${num(value)}%`).join(" · "):"—";
const screenText=(value,lang)=>value===null?"—":lang==="zh"?(value?"命中":"未命中"):(value?"Screen":"Quiet");
const COPY={
  zh:{title:"美国玉米：2012–2019 历史研究",mode:"回顾性分析 · 不是当时实时重建",intro:"使用现在取得的历史天气和 1991–2020 常年值，重放原有筛查。官方报告保留各自发布日期，但整个分析仍有回顾偏差；不是因果证明，也不是预测能力验证。",
    unavailable:"历史研究资料不可用；不以零风险代替。",loading:"正在读取历史研究资料…",season:"研究年份",region:"地区",all:"十州总览",coverage:"完整天气窗口",weeks:"出现筛查的周数",maximum:"最高关联产量份额",cumulative:"累计关联份额·周",weight:"上一年产量权重",pit:"当时可知的完整重建：不可用（缺历史天气发布版本和当时可用常年值）。",
    chain:"天气潜在暴露 ｜ 官方作物状况 ｜ 官方供应估计演变：并列证据，不推断因果。",table:"逐周天气与官方进度（可横向滚动）",end:"天气周末 / 评估日期",stage:"日历阶段 / 官方进度",heat:"高温",moisture:"水分不足",condition:"优良率",conditionDate:"报告周末",rain:"降雨距平 mm",temp:"最高温均值距平 °C",root:"根区湿润度距平",share:"全国产量权重",comparison:"后续官方状况比较",lag:"滞后周数",pairs:"配对州周",exposed:"有暴露配对",fp:"暴露后未降 ≥5 点",fn:"无暴露但降 ≥5 点",change:"暴露后平均变化（百分点）",post:"暴露结束后改善 / 配对数",rule:"比较精确相隔 1、2、4 周的优良率。下降 ≥5 个百分点只是研究分类；未下降不等于没有损伤，下降也不能归因于天气。缺报不计为正常。",
    supply:"USDA 产量与单产估计演变",published:"实际发布日期",yield:"单产 bu/acre",production:"产量 千 bushels",area:"收获面积 千 acres",outcome:"8 月 → 收获后年报",notFinal:"年报是该次发布估计，不是最新最终值。这里的修订可能已在 8 月前发生，也不证明天气导致变化。",diagnostic:"阈值与代表点诊断",threshold:"全八季筛查敏感性（不改线上规则）",spatial:"爱荷华州中心点与东／西点：高温命中不同的周数",limit:"十州一个点/州；比例只是命中点所在州的产量份额，不是受灾比例。累计份额·周会重复计入不同周，不能当成受影响产量。",sources:"来源、方法与版本",gaps:"归档排除／缺口记录",none:"没有足够的配对证据",source:"原始发布",estimated:"日历估计",normal:"筛查较少不等于正常季或无农业风险。",stages:{off:"非生长期",planting:"播种",emergence:"出苗",vegetative:"营养生长",silking:"吐丝／授粉",grainFill:"灌浆",maturity:"成熟",harvest:"收获"}},
  en:{title:"US corn: 2012–2019 historical research",mode:"Retrospective analysis · not a point-in-time reconstruction",intro:"Replay the existing screens using historical weather retrieved today and 1991–2020 normals. Official reports retain publication dates, but the full analysis remains retrospective. This is neither causal proof nor evidence of predictive skill.",
    unavailable:"Historical research unavailable; missing is not zero risk.",loading:"Loading historical research…",season:"Season",region:"Region",all:"Ten-state overview",coverage:"Complete weather windows",weeks:"Weeks with a screen",maximum:"Maximum associated production share",cumulative:"Cumulative associated share-weeks",weight:"Prior-year production weights",pit:"Full point-in-time reconstruction: unavailable (historical weather-delivery versions and then-available normals missing).",
    chain:"Potential weather exposure | official crop condition | official supply evolution: separate evidence, not causal inference.",table:"Weekly weather and official progress (scroll horizontally)",end:"Weather week ending / evaluation date",stage:"Calendar stage / official progress",heat:"Heat",moisture:"Moisture deficit",condition:"Good/excellent",conditionDate:"Report week ending",rain:"Rain anomaly mm",temp:"Mean maximum anomaly °C",root:"Root wetness anomaly",share:"National production weight",comparison:"Subsequent official condition",lag:"Lag weeks",pairs:"Paired state-weeks",exposed:"Exposed pairs",fp:"Exposure without ≥5 point decline",fn:"Quiet despite ≥5 point decline",change:"Mean change after exposure (points)",post:"Improvement after stress / pairs",rule:"Compare exact 1, 2 and 4 week good/excellent changes. A ≥5 point decline is a research convention, not ground-truth damage. Missing reports are not normal conditions; deterioration is not attributed to weather.",
    supply:"USDA production and yield estimate evolution",published:"Actual publication date",yield:"Yield bu/acre",production:"Production 1000 bushels",area:"Harvested area 1000 acres",outcome:"August → post-harvest annual report",notFinal:"The annual report is that publication's estimate, not the latest final value. Revisions may already have occurred before August and do not establish weather causation.",diagnostic:"Threshold and point diagnostics",threshold:"All eight seasons: sensitivity only (live rules unchanged)",spatial:"Iowa center versus west/east point: heat-discordant weeks",limit:"One point per state. Shares refer to state production associated with screened points, not affected production. Share-weeks repeat exposure across weeks and are not damaged output.",sources:"Sources, method & versions",gaps:"Excluded archive / gap records",none:"Insufficient paired evidence",source:"Original publication",estimated:"Calendar estimate",normal:"Few screens do not establish a normal or risk-free season.",stages:{off:"Off season",planting:"Planting",emergence:"Emergence",vegetative:"Vegetative",silking:"Silking/pollination",grainFill:"Grain fill",maturity:"Maturity",harvest:"Harvest"}}
};
export function CornHistoryView({data,lang="zh"}) {
  const [year,setYear]=useState(data?.seasons?.[0]?.season),[region,setRegion]=useState("all");
  const t=COPY[lang];
  if(!validCornHistory(data))return <p>{t.unavailable}</p>;
  const s=data.seasons.find(s=>s.season===+year)??data.seasons[0];
  return <div className="corn-history" id="corn-history"><h3>{t.mode}</h3><p>{t.intro}</p><p className="fs-notice">{t.pit}</p>
    <div className="fs-controls"><label className="fs-control">{t.season}<select value={s.season} onChange={e=>setYear(+e.target.value)}>{data.seasons.map(s=><option key={s.season}>{s.season}</option>)}</select></label>
      <label className="fs-control">{lang==="zh"?"逐周明细地区":"Region for weekly detail"}<select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">{t.all}</option>{config.regions.map(r=><option value={r.id} key={r.id}>{r.name[lang]}</option>)}</select></label></div>
    <p>{lang==="zh"?"地区选择仅筛选逐周明细；下方汇总与官方供应估计保持十州／全国口径。":"Region selection filters weekly detail only; summaries and official supply estimates retain ten-state/national scope."}</p>
    <p>{t.chain}</p><p>{t.weight}: {s.weightYear??"—"} · {t.coverage}: {s.stats.completeWeeks}/{s.stats.scheduledWeeks}</p>
    <p>{t.weeks}: {s.stats.exposedWeeks} · {t.maximum}: {pct(s.stats.maxExposure)} · {t.cumulative}: {num(s.stats.unionShareWeeks)}</p><p>{t.limit}</p><p>{t.normal}</p>
    <details className="fs-details"><summary>{t.table}</summary><div className="fs-calendar-scroll" tabIndex="0" role="region" aria-label={t.table}><table className="fs-calendar"><thead><tr><th>{t.end}</th><th>{t.stage}</th><th>{t.heat}</th><th>{t.moisture}</th><th>{t.temp}</th><th>{t.rain}</th><th>{t.root}</th><th>{t.condition}</th></tr></thead><tbody>
      {s.timeline.map(w=>{const r=w.regions.find(r=>r.id===region);return <tr key={w.end}><th>{w.end}<small>{w.asOf}</small></th><td>{r?<>{t.stages[r.stage.estimated]}<small>{t.share}: {pct(r.weight)}</small><small>{progressText(r.stage.officialProgress,lang)}</small></>:t.all}</td>
        <td>{r?screenText(r.weather?.heat??null,lang):pct(w.heat)}</td><td>{r?screenText(r.weather?.moisture??null,lang):pct(w.moisture)}</td>
        <td>{num(r?.weather?.maxAnomaly)}</td><td>{num(r?.weather?.rainAnomaly)}</td><td>{num(r?.weather?.rootAnomaly)}</td>
        <td>{r?.condition?<>{num(r.condition.good+r.condition.excellent)}%<small>{r.conditionWeek}</small></>:"—"}</td></tr>;})}
    </tbody></table></div></details>
    <h4>{t.comparison}</h4><p>{t.rule}</p><div className="fs-calendar-scroll" tabIndex="0" role="region" aria-label={t.comparison}><table className="fs-calendar"><thead><tr>{[t.lag,t.pairs,t.exposed,t.fp,t.fn,t.change,t.post].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{[1,2,4].map(lag=>{const c=s.comparisons[lag];return <tr key={lag}><th>{lag}</th><td>{c.pairs}</td><td>{c.exposedPairs}</td><td>{c.falsePositiveLike}</td><td>{c.falseNegativeLike}</td><td>{num(c.meanChangeAfterExposure)}</td><td>{c.postStressImproved}/{c.postStressPairs}</td></tr>;})}</tbody></table></div>
    <h4>{t.supply}</h4><p>{t.notFinal}</p>{s.supplyTimeline.length?<div className="fs-calendar-scroll" tabIndex="0" role="region" aria-label={t.supply}><table className="fs-calendar"><thead><tr>{[t.published,t.yield,t.production,t.area,t.source].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{s.supplyTimeline.map((r,i)=><tr key={i}><th>{r.publishedDate}</th><td>{num(r.yield)}</td><td>{num(r.production)}</td><td>{num(r.harvestedArea)}</td><td><a href={s.inputVersions[r.input].downloadUrl} target="_blank" rel="noreferrer">NASS ↗</a></td></tr>)}</tbody></table></div>:<p>{t.none}</p>}
    <p>{t.outcome}: {t.yield} Δ {num(s.outcome.revision?.yield.absolute)} · {t.production} Δ {num(s.outcome.revision?.production.absolute)}</p>
    <details className="fs-details"><summary>{t.diagnostic}</summary><p>{t.threshold}</p><ul>{Object.entries(data.summary.thresholdComparison).map(([key,v])=><li key={key}>{key}: {v.exposedWeeks}/{v.completeWeeks} · {num(v.shareWeeks)} share-weeks</li>)}</ul>
      <p>{t.spatial}</p><ul>{s.spatial.map(p=><li key={p.point}>{p.point}: {p.eligible?`${p.discordantWeeks}/${p.pairedWeeks}`:"—"}</li>)}</ul>
      <p>{lang==="zh"?"仅为爱荷华州少量点的高温敏感性试验；没有耕地权重或田间真值，不能证明当前空间精度足够。":"Sparse Iowa heat sensitivity only: no crop-area weights or field truth; agreement cannot establish adequate statewide resolution."}</p></details>
    <details className="fs-details"><summary>{t.sources}</summary><p>{data.methodologyVersion} · {data.protocol}</p><small style={{overflowWrap:"anywhere"}}>{data.artifactId}</small><p>{t.gaps}: {data.sourceGaps.length}</p>
      <pre style={{maxHeight:320,overflow:"auto"}}>{JSON.stringify({inputs:s.inputVersions,gaps:data.sourceGaps.filter(g=>g.period?.startsWith(String(s.season)))},null,2)}</pre></details>
  </div>;
}
export default function CornHistory({lang}) {
  const [data,setData]=useState(null),[attempted,setAttempted]=useState(false),[failed,setFailed]=useState(false);
  const load=event=>{if(!event.currentTarget.open||attempted)return;setAttempted(true);
    import("../data/cornHistory.json").then(m=>{if(!validCornHistory(m.default))throw new Error("Invalid historical artifact");setData(m.default);}).catch(()=>setFailed(true));};
  return <details className="fs-details fs-card corn-history-panel" onToggle={load}><summary>{COPY[lang].title}</summary>{data?<CornHistoryView data={data} lang={lang}/>:<p>{COPY[lang][failed?"unavailable":"loading"]}</p>}</details>;
}
